// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zywfixulltetyiaqlstf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5d2ZpeHVsbHRldHlpYXFsc3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDU2OTMsImV4cCI6MjA2NjMyMTY5M30.INpIae_KLkxjE2XgCauYmww05w8u6l0axfnnFpGci_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);